
service: lambda-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  enviroment:
    AUTH0_CLIENT_ID: ${file(./config.json):AUTH_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${file(./config.json):AUTH_CLIENT_SECRET}

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  # Test function to ensure pack was deployed successfully
  hello:
    handler: handler.hello
    events:
      - http:
          path: api/hello
          method: get

  # Primary Lambda that triggers upon upload to working bucket
  uploadImage:
    handler: handler.uploadImage
    events:
      - s3: 
          bucket: ${file(./config.json):WORKING_BUCKET}
          event: s3.ObjectCreated

# Resources
#resources:
#  Resources:
#    WorkingBucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ${file(./config.json):WORKING_BUCKET}

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
