
service: lambda-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  memorySize: 512

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:

  # Resize Lambda
  uploadImage:
    handler: handler.uploadImage
    events:
      - s3: ${self:provider.stage}-lambdatest
      - http:
          method: post
          path: /api/resize-images
          cors: true
          integration: lambda
          request:
            #parameters:
            #  querystrings:
            #    source_url: true
            #    resize_option: false
            #    dest_s3_bucket: false
            #    dest_s3_prefix: false
          response:
            template: $input.path('$')
            statusCodes:
              201:
                pattern: 

# Resources
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
